extends: '@atomix/eslint-config'
parser: babel-eslint
rules:
  max-len: off
  camelcase: 1
  no-console: 1
  no-magic-numbers: 1
  no-param-reassign: 1
  prettier/prettier: off
  prefer-rest-params: 1
  no-underscore-dangle: 1
  unicorn/filename-case: off
  class-methods-use-this: 1
  import/no-default-export: off
  curly:
    - error
  comma-dangle:
    - error
    - always-multiline
  id-length:
    - error
    -
      min: 2
      exceptions:
        - i
        - x
        - y
        - e
  id-match:
    - error
    - "^(([A-Za-z0-9]+){2,})|([A-Z][A-Z_0-9]+)$"
    -
      properties: false
      onlyDeclarations: true
  indent:
    - error
    - 2
    -
      SwitchCase: 1
  quotes:
    - error
    - single
  semi:
    - error
    - never
